# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialBlock.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialBlock(object):
    def setupUi(self, DialBlock):
        DialBlock.setObjectName("DialBlock")
        DialBlock.resize(434, 73)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(DialBlock)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(DialBlock)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(DialBlock)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_5 = QtWidgets.QLabel(DialBlock)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(DialBlock)
        self.doubleSpinBox_3.setMinimum(-1000000000.0)
        self.doubleSpinBox_3.setMaximum(1000000000.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_3)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(DialBlock)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(DialBlock)
        self.doubleSpinBox.setMinimum(-1000000000.0)
        self.doubleSpinBox.setMaximum(1000000000.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.label_2 = QtWidgets.QLabel(DialBlock)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(DialBlock)
        self.doubleSpinBox_2.setMinimum(-1000000000.0)
        self.doubleSpinBox_2.setMaximum(1000000000.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_2)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.dial = QtWidgets.QDial(DialBlock)
        self.dial.setObjectName("dial")
        self.horizontalLayout_2.addWidget(self.dial)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalSlider = QtWidgets.QSlider(DialBlock)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(DialBlock)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(DialBlock)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.pushButton = QtWidgets.QPushButton(DialBlock)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DialBlock)
        self.doubleSpinBox.valueChanged['double'].connect(DialBlock.lowChanged)
        self.doubleSpinBox_3.valueChanged['double'].connect(DialBlock.valueChanged)
        self.doubleSpinBox_2.valueChanged['double'].connect(DialBlock.highChanged)
        self.dial.sliderMoved['int'].connect(DialBlock.dialTurned)
        self.horizontalSlider.sliderMoved['int'].connect(DialBlock.sliderMoved)
        self.radioButton.toggled['bool'].connect(DialBlock.linSelected)
        self.radioButton_2.toggled['bool'].connect(DialBlock.logSelected)
        self.pushButton.clicked.connect(DialBlock.xPressed)
        self.dial.valueChanged['int'].connect(DialBlock.dialTurned)
        self.horizontalSlider.valueChanged['int'].connect(DialBlock.sliderMoved)
        self.lineEdit.editingFinished.connect(DialBlock.nameChanged)
        QtCore.QMetaObject.connectSlotsByName(DialBlock)

    def retranslateUi(self, DialBlock):
        _translate = QtCore.QCoreApplication.translate
        DialBlock.setWindowTitle(_translate("DialBlock", "Form"))
        self.label_4.setText(_translate("DialBlock", "Name"))
        self.label_5.setText(_translate("DialBlock", "Value"))
        self.label.setText(_translate("DialBlock", "LOW"))
        self.label_2.setText(_translate("DialBlock", "HIGH"))
        self.radioButton.setText(_translate("DialBlock", "LIN"))
        self.radioButton_2.setText(_translate("DialBlock", "LOG"))
        self.pushButton.setText(_translate("DialBlock", "Remove"))

